tap 'nikitabobko/tap'
tap 'FelixKratz/formulae'

# Build dependencies used by mise-managed language runtimes.
brew 'autoconf'
brew 'automake'
brew 'pkg-config'
brew 'libtool'
brew 'libffi'
brew 'openssl@3'
brew 'zlib'
brew 'gmp'
brew 'libyaml'
brew 'readline'

# Host CLIs and macOS integrations.
brew 'borders'
brew 'colima'
brew 'container'
brew 'fish'
brew 'kanata'
brew 'mas'
brew 'mise'
brew 'sketchybar'
brew 'stow'
brew 'zsh-autosuggestions'
brew 'zsh-history-substring-search'
brew 'zsh-syntax-highlighting'

cask 'font-jetbrains-mono-nerd-font'
cask 'font-sketchybar-app-font'
cask 'aerospace'
cask 'bitwarden'
cask 'brave-browser'
cask 'cursor'
cask 'docker-desktop'
cask 'figma'
cask 'notion'
cask 'obsidian'
cask 'postman'
cask 'raycast'
cask 'shottr'
cask 'slack'
cask 'tailscale-app'
cask 'visual-studio-code'
cask 'wezterm'
cask 'whatsapp'
cask 'zoom'

mas 'Xcode', id: 497799835
